deploy:
  environment: production
  image: python:latest
  variables:
    S3_BUCKET_NAME: bulik.dev
  before_script:
    - pip install awscli
  script:
    - aws s3 cp ./ s3://$S3_BUCKET_NAME/ --recursive --exclude "*" --include "index.html"
